/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RecordingPreviewScheduler */

#ifndef _Included_RecordingPreviewScheduler
#define _Included_RecordingPreviewScheduler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler
 * Method:    startEncoding
 * Signature: (IIIIZ)V
 */
JNIEXPORT void JNICALL Java_com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler_startEncoding
  (JNIEnv *, jobject, jint, jint, jint, jint, jboolean, jstring);

/*
 * Class:     com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler
 * Method:    stopEncoding
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler_stopEncoding
  (JNIEnv *, jobject);

/*
 * Class:     com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler
 * Method:    switchCameraFacing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler_switchCameraFacing
  (JNIEnv *, jobject);

/*
 * Class:     com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler
 * Method:    prepareEGLContext
 * Signature: (Ljava/lang/Object;III)V
 */
JNIEXPORT void JNICALL Java_com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler_prepareEGLContext
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler
 * Method:    createWindowSurface
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler_createWindowSurface
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler
 * Method:    resetRenderSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler_resetRenderSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler
 * Method:    destroyWindowSurface
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler_destroyWindowSurface
  (JNIEnv *, jobject);

/*
 * Class:     com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler
 * Method:    destroyEGLContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler_destroyEGLContext
  (JNIEnv *, jobject);

/*
 * Class:     com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler
 * Method:    notifyFrameAvailable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_camerapreviewrecorder_camera_preview_RecordingPreviewScheduler_notifyFrameAvailable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
